#!/bin/bash
# ~/.bash_profile

# Add extra directories to PATH.
[[ -d ~/.local/bin ]] && export PATH="${HOME}/.local/bin:${PATH}"

JB="${HOME}/.local/share/JetBrains/Toolbox/scripts"
[[ -d "${JB}" ]] && export PATH="${PATH}:${JB}"


# Init pyenv by adding it to PATH.
if [[ -x /usr/bin/pyenv ]]; then
  eval "$(pyenv init --path)"
fi


# Set other environment variables.
export LC_TIME=en_DK.UTF-8
export TIME_STYLE=long-iso

export EDITOR=nvim
export OPENER=mimeopen

export XDG_CACHE_HOME=${HOME}/.cache
export XDG_CONFIG_HOME=${HOME}/.config
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_STATE_HOME=${HOME}/.local/state

export FZF_DEFAULT_OPTS='--cycle --layout=reverse --border --height=90% --preview-window=wrap --marker="*"'

export _ZO_ECHO=1


# Run .bashrc
[[ -r ~/.bashrc ]] && . ~/.bashrc

