#!/bin/zsh
# ~/.zprofile

# Set system environment variables.
export LANG=en_US.UTF-8
export EDITOR=vim

export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"


# Configure MacPorts.
#[[ -d /opt/local/bin ]] && export PATH="/opt/local/bin:/opt/local/sbin:${PATH}"


# Configure Homebrew.
export HOMEBREW_NO_ANALYTICS=1
eval "$(/opt/homebrew/bin/brew shellenv)"


# Add extra directories to PATH.
[[ -d ~/.local/bin ]] && export PATH="${HOME}/.local/bin:${PATH}"


# Set apps environment variables.
export FZF_DEFAULT_OPTS='--cycle --layout=reverse --border --height=90% --preview-window=wrap --marker="*"'
export _ZO_ECHO=1

