#!/bin/sh

sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap

# Merge in defaults and keymaps
[ -f "$sysresources" ]  && xrdb -merge $sysresources
[ -f "$sysmodmap" ]     && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ]    && xmodmap "$usermodmap"

# Start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


# Set environment variable for Qt applications (qt5ct/kvantum-qt5)
# References:
# - wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications
# - wiki.archlinux.org/title/Qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE_Plasma
[ -x /usr/bin/qt5ct ] && export QT_QPA_PLATFORMTHEME=qt5ct

# Monitor configuration (check monitors with 'xrandr --listmonitors')
xrandr --output HDMI-0 --primary --left-of DP-3 --output DP-3 --auto

# NVIDIA settings
# Reference: https://wiki.archlinux.org/title/NVIDIA/Troubleshooting#Avoid_screen_tearing
nvidia-settings --assign CurrentMetaMode="HDMI-0: nvidia-auto-select +0+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, DP-3: nvidia-auto-select +2560+270 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"

# Tweak mouse wheel behavior
imwheel --buttons 45

# Remap mouse buttons
# 1: left, 2: middle, 3: right, 4/5: mouse wheel up/down, 6/7: mouse wheel left/right, 8/9: back/forward
# Default | Custom
#   2 8   |   1 2
#    .    |    .
#   1 3   |   1 3
xinput --set-button-map 'Kensington Expert Mouse' 1 1 3 4 5 6 7 2 2
# Decrease pointer acceleration
xinput --set-prop 'Kensington Expert Mouse' 'libinput Accel Speed' -0.5

# Set mouse cursor
# Reference: https://wiki.archlinux.org/title/Cursor_themes#Change_X_shaped_default_cursor
xsetroot -cursor_name left_ptr

# Keyboard configuration (man xkeyboard-config)
# - Use Win+Space to toggle keyboard layouts
setxkbmap -layout 'us,us(intl)' -option grp:win_space_toggle
# - CapsLock as Ctrl, both Shifts to toggle CapsLock
setxkbmap -option ctrl:nocaps,shift:both_capslock
# Enable numlock in X
numlockx

# Execute Xmonad
exec xmonad > ~/.var/xsession-errors 2>&1
