#!/bin/bash
# ~/.bashrc

# If not running interactively, don't do anything.
[[ $- != *i* ]] && return


# Don't put duplicate lines or lines starting with space in the history and erase duplicate lines.
HISTCONTROL=ignoreboth:erasedups
# Append to the history file, don't overwrite it.
shopt -s histappend


# Useful aliases.
alias ls='ls --color=auto'
alias ll='ls -l'
alias la='ls -la'

alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

if command -v nvim &> /dev/null; then
  alias vi='nvim --clean'
else
  alias vi='vim -u NONE'
fi


# Find packages that provide unavailable commands.
[[ -r /usr/share/doc/pkgfile/command-not-found.bash ]] && . /usr/share/doc/pkgfile/command-not-found.bash


# fzf keybindings and completion
# Ctrl+r: search shell command history
# Ctrl+t: list files in current directory
# Alt+c:  change directory
[[ -r /usr/share/fzf/key-bindings.bash ]] && . /usr/share/fzf/key-bindings.bash
[[ -r /usr/share/fzf/completion.bash ]] && . /usr/share/fzf/completion.bash


# Load zoxide
[[ -x /usr/bin/zoxide ]] && eval "$(zoxide init bash)"
