#!/bin/bash

sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
userresources=$XDG_CONFIG_HOME/X11/Xresources
usermodmap=$XDG_CONFIG_HOME/X11/Xmodmap

# Merge in defaults and keymaps
[ -f "$sysresources" ]  && xrdb -merge $sysresources
[ -f "$sysmodmap" ]     && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ]    && xmodmap "$usermodmap"

# Start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi


# Set environment variable for Qt applications (qt5ct/kvantum-qt5)
# References:
# - wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications
# - wiki.archlinux.org/title/Qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE_Plasma
[ -x /usr/bin/qt5ct ] && export QT_QPA_PLATFORMTHEME=qt5ct

# Set environment variable for Java applications
# Reference:
# - https://wiki.haskell.org/Xmonad/Frequently_asked_questions#Preferred_Method
export _JAVA_AWT_WM_NONREPARENTING=1

# Monitor configuration (monitor 1: 3840x2160 / monitor 2: 2560x1440)
# References:
# - https://wiki.archlinux.org/title/Xorg#Display_size_and_DPI
# - https://wiki.archlinux.org/title/Xrandr#Configuration_using_arandr
# - check monitor with 'xrandr --listmonitors'
# NVIDIA
#xrandr --dpi 96 --output DP-0 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output HDMI-0 --mode 2560x1440 --pos 2560x0 --rotate normal --output DP-1 --off --output DP-2 --off --output DP-3 --off --output DP-4 --off --output DP-5 --off
# Intel
xrandr --dpi 96 --output HDMI-2 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP-1 --mode 2560x1440 --pos 2560x0 --rotate normal

# Remap mouse buttons
# 1: left, 2: middle, 3: right, 4/5: mouse wheel up/down, 6/7: mouse wheel left/right, 8/9: back/forward
# Default | Custom
#   2 8   |   1 2
#    .    |    .
#   1 3   |   1 3
xinput --set-button-map 'Kensington Expert Mouse' 1 1 3 4 5 6 7 2 2
# Decrease pointer acceleration
xinput --set-prop 'Kensington Expert Mouse' 'libinput Accel Speed' -0.5

# Set mouse cursor
# Reference: https://wiki.archlinux.org/title/Cursor_themes#Change_X_shaped_default_cursor
xsetroot -cursor_name left_ptr

# Keyboard configuration (man xkeyboard-config)
# - Use Win+Space to toggle keyboard layouts
setxkbmap -layout 'us,us(intl)' -option grp:win_space_toggle
# Use menu key as compose key (e.g. type menu , c to get cedilla)
# https://en.wikipedia.org/wiki/Compose_key
setxkbmap -option compose:menu
# Bind special keys
xbindkeys -f $XDG_CONFIG_HOME/X11/xbindkeysrc

# Screen locking
# References:
# - https://wiki.archlinux.org/title/Session_lock
# - https://github.com/google/xsecurelock
# - https://wiki.archlinux.org/title/Display_Power_Management_Signaling
# Dim the screen after 600s of inactivity (xsecurelock dimmer), lock the screen 30s later (betterlockscreen)
xset s 600 30
export XSECURELOCK_WAIT_TIME_MS=30000  # Time to keep dimmer active (from notification until screen lock)
xss-lock --notifier=/usr/lib/xsecurelock/dimmer -- betterlockscreen --lock --quiet --time-format "%H:%M" &
# Turn off monitors after 900s of inactivity
xset dpms 900 900 900
readarray -t WP < <(ls ~/Pictures/Wallpapers/variety/**/*.jpg | shuf -n 2)
betterlockscreen --update ${WP[0]} --update ${WP[1]} &

# Autostart desktop apps
# Polkit authentication agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Xsettings daemon
xsettingsd &
# Xorg compositor
picom &
# Notification daemon
dunst &
# Storage devices automounter
udiskie --tray &
# Media player controller
playerctld daemon &
# Wallpaper setter
~/.fehbg &
variety &
# Color temperature shifter
redshift &
# Manually disable screensaver
caffeine &
# Password manager
keepassxc ~/Documents/Passwords.kdbx &
# Clipboard manager
copyq &
# Dock
XDG_SESSION_TYPE=x11 plank -n left_dock &
XDG_SESSION_TYPE=x11 plank -n right_dock &
# Cloud files sync
dropbox &


exec qtile start
