config_version: 2
settings:
  bindings.commands:
    global:
      normal:
        ',M': hint links spawn vlc.bat {hint-url}
        ',m': spawn vlc.bat {url}
        <Ctrl+Shift+Tab>: tab-prev
        <Ctrl+Tab>: tab-next
      command:
        <Ctrl+p>: completion-item-focus --history prev
        <Ctrl+n>: completion-item-focus --history next
        <Ctrl+l>: command-accept
        <Shift+PgUp>: command-history-prev
        <Shift+PgDown>: command-history-next
  colors.webpage.preferred_color_scheme:
    global: dark
  content.autoplay:
    global: false
  content.cookies.accept:
    global: no-3rdparty
  content.cookies.store:
    global: false
  content.notifications.enabled:
    global: false
  content.prefers_reduced_motion:
    global: true
  content.proxy:
    global: http://localhost:3128
  downloads.position:
    global: bottom
  editor.command:
    global:
    - gvim
    - -f
    - '{file}'
    - -c
    - normal {line}G{column0}l
  editor.encoding:
    global: utf-8
  fonts.default_family:
    global: SauceCodePro NF
  fonts.default_size:
    global: 11pt
  hints.chars:
    global: asdhjkl
  qt.args:
    global:
    - autoplay-policy=user-gesture-required
  qt.process_model:
    global: process-per-site
  scrolling.bar:
    global: always
  session.lazy_restore:
    global: true
  statusbar.position:
    global: bottom
  tabs.background:
    global: true
  tabs.mousewheel_switching:
    global: false
  tabs.position:
    global: top
  tabs.width:
    global: 20%
  url.searchengines:
    global:
      ',d': https://duckduckgo.com/?q={}
      ',g': https://google.com/search?q={}
      ',gs': https://scholar.google.com/scholar?q={}
      DEFAULT: https://search.brave.com/search?q={}
