# Reference: https://alacritty.org/config-alacritty.html

## General

[shell]
program = "/usr/bin/tmux"


## Window

[window]
padding = { x = 2, y = 2 }
dynamic_padding = true
opacity = 0.9


## Font

[font]
size = 9.0
normal = { family = "Hack Nerd Font Mono" }


## Colors

# Tokyo Night Storm scheme (https://github.com/alacritty/alacritty-theme/blob/master/themes/tokyo-night-storm.toml)

[colors.primary]
background = "#24283b"
foreground = "#a9b1d6"

[colors.normal]
black   = "#32344a"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#ad8ee6"
cyan    = "#449dab"
white   = "#9699a8"

[colors.bright]
black   = "#444b6a"
red     = "#ff7a93"
green   = "#b9f27c"
yellow  = "#ff9e64"
blue    = "#7da6ff"
magenta = "#bb9af7"
cyan    = "#0db9d7"
white   = "#acb0d0"


## Selection

[selection]
save_to_clipboard = true


## Cursor

[cursor]
style = { blinking = "Always" }


## Mouse

[mouse]
hide_when_typing = true


## Keyboard

[keyboard]
bindings  = [
	{ key = "Insert", mods = "Shift", action = "Paste" }
]

